# Generated by Django 5.1.1 on 2024-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Coke', 'Coke'), ('pepsi', 'pepsi'), ('sprite', 'sprite'), ('Fanta', 'Fanta'), ('Coke Zero', 'Coke Zero')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
